[project]
name = "duplexchat-runtime"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "duplex-pipelines",
    "torch==2.8.0",
    "torchaudio==2.8.0",
    "torchcodec==0.7.0",
    "soundfile",
    "pydub",
    "librosa",
    "demucs==4.0.1",
    "pyannote.audio==3.3.2",
    "speechbrain==1.0.3",
    "diffusers<=0.30.0",
    "huggingface-hub>=0.34.0,<1.0",
    "wrapt",
    "onnx==1.22.0",
    "onnxruntime==1.22.1",
    "numpy",
    "Cython",
    "packaging",
    "omegaconf",
    "hydra-core",
    "pytorch-lightning",
    "transformers~=4.57.0",
    "nemo_toolkit[asr] @ git+https://github.com/NVIDIA-NeMo/Speech.git@ca3f93a516ff172e32951928aea6f96a977a7600",
    "protobuf~=5.29.5",
    "tqdm",
]


[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
duplex-pipelines = { path = "../..", editable = true }

[tool.uv.extra-build-dependencies]
youtokentome = ["Cython"]
