[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "duplex-pipelines"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"

[tool.setuptools.packages.find]
where = ["."]
include = ["core*", "scripts*"]

[tool.setuptools.package-dir]
"" = "."
cholimex = "pipeline/cholimex/src/cholimex"
duplexchat = "pipeline/duplexchat/src/duplexchat"
sommelier = "pipeline/sommelier/src/sommelier"

[tool.uv.extra-build-dependencies]
youtokentome = ["Cython"]
